themes:
  AI萌娃:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAA_zexO5aHT-l4F6A6tEMGM_Pe1BYbAYtSFRtg-SSCQvJK8KZ59YmE31ZZ67FP_XpA"
      - "https://www.douyin.com/user/MS4wLjABAAAAkfISilB6zeZTIzLYAFuOWXkHvzo7X0J7kkqHyiolARVC2Rh1EUwUhvKh1T8qvEsD"
      - "https://www.douyin.com/user/MS4wLjABAAAAHz0Bg7VgSe9odZuUpfSM-9THmmGTCfSEe_a0ULll9Zc"
      - "https://www.douyin.com/user/MS4wLjABAAAAn0Lv146sn-Jd4V1ZxB19Fsap6htzTyRMv1CcVjZ4bGWBeLQW4X3Yjjn-z-MYamV9"
      - "https://www.douyin.com/user/MS4wLjABAAAAxLdyNLKXp52qo_wWHDSfq0ylohqxm298AeRbHPS3Wzo"
      - "https://www.douyin.com/user/MS4wLjABAAAAHiIe9jN3nyc9wToCeN21986VJedcUHHOZor35PUQC_MwsN3bZu0ftMp8SZbcq9XS"
      - "https://www.kuaishou.com/profile/3xrf8d4e2b43rfk"
      - "https://www.kuaishou.com/profile/3xshdiqc6m7m5ay"
      - "https://www.douyin.com/user/MS4wLjABAAAA8NxCMTP_GCatbYVwuadbUQsdmAzuGYgtHW-6Pzq8ZMHkeOtP6VjahZ3U13LYqcOB"
      - "https://www.douyin.com/user/MS4wLjABAAAA0D_uW7FXz4TsOA2dZQFZKsV5F_qzX-Vkq9vaauphpSG4haGCIPcvjDgryCqUIT2l"

  中国中式妆容:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAgHeudGyby_zzEEGcv7sTQ01MNKWos0i6fRp2RyRIfBI"
      - "https://www.douyin.com/user/MS4wLjABAAAA4EWhc2NqONE1gqKoCoiZLfiQcTtyIBTRrj1xcId-AV0"
      - "https://www.douyin.com/user/MS4wLjABAAAA2I0IFpg_zThhxlpSlvEsxPn74ORBrQUuKD6o6aaRyiE"
      - "https://www.douyin.com/user/MS4wLjABAAAAmcKClOHnQF7gRb_rgP7Gvf16sgfEGxInXraKTFDla2w"
      - "https://www.douyin.com/user/MS4wLjABAAAAIRQRRuDFQvzWX4finu2-ZEtlxI4CVONTe5IHu5udwzs"
      - "https://www.douyin.com/user/MS4wLjABAAAAmokFh0aftpg8M-T1mkM9yuaacC4nTkkbZIugXn5yUiY"
      - "https://www.douyin.com/user/MS4wLjABAAAA2MpRxY0JuyCCHGVDpjz5cObi6lBum9MIcfgZKXuTdxM"
      - "https://www.douyin.com/user/MS4wLjABAAAAZge6SVRa1RniKvhMLSirR7UQKF2Qqi3h9VLROrkJ_v8"
      - "https://www.douyin.com/user/MS4wLjABAAAAJFNT3Mpz3kK2jOwiz8-sVoD7k5d3EWTUxTjzP5NNofyru1PI28F0eBodW1eUmlPS"
      - "https://www.douyin.com/user/MS4wLjABAAAARrgRYOhYihodh5LLZUk7Krc7EC6001Pl7-uJu9dPNsfUaaLMVLDYZTRCM-4oRpKC"
      - "https://www.douyin.com/user/MS4wLjABAAAA286wZ9QAVe33StDXzTWmlFYEuEg0JculkTEdHo8fCuekGJ4o9ObVBzwCYPzC_Lf_"

  中国帅哥美女:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAA2C9BqsWe_-ZTbAbuRuoBkNpjVxae_DPa-GT4tiZtkSZMgSAe8HwixHBcK6y06H1G"
      - "https://www.douyin.com/user/MS4wLjABAAAAVfrwdhUhZ5BbutA6PcbrbjJH_v7fClSG6le5tT27ti4"
      - "https://www.kuaishou.com/profile/3x3nh49hzggz6vq"
      - "https://www.kuaishou.com/profile/3xbh9qafpuyg2wc"
      - "https://www.douyin.com/user/MS4wLjABAAAA69hZ4_OSQi6-9xeUqeM1bcI3hL4VeDhUfy93UN7PmGjsXjykwzs0HNIy4CxK0Q9f"
      - "https://www.douyin.com/user/MS4wLjABAAAAaBqqmQ3ogRvXc3h9XeJZTGpMpYV4VaM0QzdezdfRWZ4"
      - "https://www.douyin.com/user/MS4wLjABAAAAy_A7pc7yNCOx0vxMFpao_Urza6RxsAyNgm4rcpuDf1E"
      - "https://www.kuaishou.com/profile/3xmfycsejg2vhqu"

  中国机器人:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAl9fsQrpTtHnWoBwqBTZFNHXz6S63gN2uQ45XYHbn1cM"
      - "https://www.douyin.com/user/MS4wLjABAAAATpe0vaPWkvDtK9QXYSdvhakK7ditw1dEFpamupWruVA"
      - "https://www.douyin.com/user/MS4wLjABAAAAH-qAMNI_5mifascJS91Oex6LBrtxk_L6_erypnnJRSY"
      - "https://www.douyin.com/user/MS4wLjABAAAAB_Bc0_s6JoY_DASTXLc32Rs4XECpVmBTILdUspgnIjXat99lMYC--Z5Ew-wvbaNd"
      - "https://www.douyin.com/user/MS4wLjABAAAA9_LEgH0c1g-n4xcvklxHKB0JFo_vYzwiO7kBIEpGofE1CasMSaNrOcUuXkCTbQoO"
      - "https://www.douyin.com/user/MS4wLjABAAAAfckLF0QWoZ6qumqgzO4mqGXdzBHhQF5sB8s6BXU6tVo"
      - "https://www.douyin.com/user/MS4wLjABAAAA7EcblI_nMozz6vgFKQW9U_ll56r24kTvK57V_NHmFS0"
      - "https://www.douyin.com/user/MS4wLjABAAAAAvvpUAzdyOK5GzkhiJbISNkjqTdaCgKoJxJ_hF2v00UKsEvgWrak12yW4ABTGiOh"
      - "https://www.douyin.com/user/MS4wLjABAAAAuaMtpNFpw_v_YAK0OdRhkE9TfA255eLAkT8gcAIvFwTrWzdmcId9oxH2ARD1O0DV"
      - "https://www.douyin.com/user/MS4wLjABAAAAGLsOyM67uoTuFyPY9tyhNhdLhhBPmfEQcYPF-HWO9915Ud5Swt2S8dARWcUS9t4g?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA-zT2LXqcLps6_2jXBNjL4Gd1r36tGHZSGs4QpO--vz4"

  中国IP盲盒:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAAKuO_AURx-6IlOx1GbUyeI1oqiaqCQK9xSjHcRdVyl7YS0pU_IUMLp3wrmYsdhXt"
      - "https://www.douyin.com/user/MS4wLjABAAAA4xe0RC0JIpuycMU6ERZMTbhEZYWajhA45zKUB6l5f6_2Yz4zSmpTTGFzROpziRRM"
      - "https://www.douyin.com/user/MS4wLjABAAAAsQ1JvAV6LI2yv1KX6MaWa5XKkYwLzhsYRbfB8ECbpC7EGE3drWNjRASztQe_TKnQ"
      - "https://www.douyin.com/user/MS4wLjABAAAAWQ-URuZ2_HmK9f2CBecDR64AetqTScATa3TUqpcg7SU"
      - "https://www.douyin.com/user/MS4wLjABAAAAX8Li6PmVBCt75ZvVEUYvM7ys62Ypadwxl2nJIZMXstfR7moztDAjagAIOpvmqwYu"
      - "https://www.douyin.com/user/MS4wLjABAAAAPy5csVnk9Wi9uZHO8xmBHwy9WKdckoD85K0z7_3y4t1F3P8dMxnlP7Gov7qcylf3"
      - "https://www.kuaishou.com/profile/3xhsa8yb9547tfe"

  魔性舞蹈:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAm_wUBNrb1-LfI_AkOx59h7m_skgTBJ5gZF37tsoHoXM?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA0wnLiPLxHSe8UVK9Ds4t0Zgx8lTnf-1lib7w0vM8AJ4DRVn0zSBwRSST_Q739p5T"
      - "https://www.kuaishou.com/profile/3xm5pxjrcqgz93c"
      - "https://www.douyin.com/user/MS4wLjABAAAAOwcNuH4cCLu1PMaWz82AH8kzTp-nkkxcb5OuWNYGhSY?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA7EfmPQGWJqzl_wvC-HKir8XlYiLgKSjaEPOS3ULXMzc"
      - "https://www.douyin.com/user/MS4wLjABAAAASN8BOgHTbdvV7CQrYJAcDRMcay_2d_vOmWPcn-9Co_w?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAATicuDM0DSJFqhnXyKBBltSScOqAgFqyh0w0IrUUdBd0?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA-2N7la2zNv8hVwZ4fAwVa5QpiiEKj1WrLeOFWyV_1Ns?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAx6Lhd2mhDub8e3C5YPNk1ow-inCnpF59v4TmSsOPpKg?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAGn9Pe-uPjg_cLhEAslWGP7yDIbL24-vKp0TMy7E8TZZnJ1e7UJMZ7p50jei4yKe3?from_tab_name=main"

  中国服饰变装:
    source_accounts:
      - "https://www.kuaishou.com/profile/3xckw4vk4rwtbqy"
      - "https://www.kuaishou.com/profile/3xhfz6tnyw7t69e"
      - "https://www.kuaishou.com/profile/3xn6kbexb25zhpe"
      - "https://www.kuaishou.com/profile/3x6zcjuc4ukbaxi"
      - "https://www.kuaishou.com/profile/3xr2mf3c4t4pp7i"
      - "https://www.kuaishou.com/profile/3xd6ai45jnrg254"
      - "https://www.kuaishou.com/profile/3xpr7p3tg2duf5c"
      - "https://www.kuaishou.com/profile/3xqeet7epqegkd9"
      - "https://www.kuaishou.com/profile/3xzsd6jhjfmqp84"
      - "https://www.kuaishou.com/profile/3xmgabqk9xzw8xa"
      - "https://www.kuaishou.com/profile/3xktjuptnhnmquy"
      - "https://www.douyin.com/user/MS4wLjABAAAANi3baNeciD0QK5AKs_3DbJdO7gzA0-tLRYlDTTi6spQ"
      - "https://www.douyin.com/user/MS4wLjABAAAARd4iHtrGMZ-Bwc1WNi6ZnU-rL5qn1lTmkn4i8lAGJNM"
      - "https://www.douyin.com/user/MS4wLjABAAAAWEtZom3L-VqMnnaeMcepf_aHDZkqxz_hO_ZtSCFb9JaaaRN25_Qr-SlBfwyGUHTl"

  魔性音乐:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAALlt4rVGyZxOh1_eFF7poEl60jplGuCVhQXsZp9G1I04"
      - "https://www.douyin.com/user/MS4wLjABAAAAtUkttxFP_-Rqef7oumBmSGml77knl3qXO97W1qXRGpQ"
      - "https://www.douyin.com/user/MS4wLjABAAAAm8PLIioPG6V0-KdTqNlFUfFfM-7yP8wJ6K870mbhKlNj_kTzAMSJPxf68lEpN_l4"
      - "https://www.douyin.com/user/MS4wLjABAAAA-CgaCH-g9IqGDyCGovG_6Xdk77emjjtSEDaSol4vgac"
      - "https://www.douyin.com/user/MS4wLjABAAAA0OL7H1So_im01zHYc5Ig1K0YQ0hEzZaTzRCTu11Zuoc"
      - "https://www.douyin.com/user/MS4wLjABAAAAzGLd7yrcaKYhPFyMsNliGbBUQ5uG_ofKp017giIzh-c"
      - "https://www.douyin.com/user/MS4wLjABAAAA8eFMdwSdiuFo5tGiE2FkxLEp1OJvk3arXNJjSXJsWTiK3_0-Jw9OXMOnbqO2ENWB?from_tab_name=main"
      - "https://www.kuaishou.com/profile/3xbj58wur52a7ig"
      - "https://www.kuaishou.com/profile/3xaun2d97mtiwv2"
      - "https://www.kuaishou.com/profile/3xu8ntn3ebeqxfq"

  动物萌宠:
    source_accounts:
      - "https://www.kuaishou.com/profile/3xxq7zk6ctyfmb6"
      - "https://www.kuaishou.com/profile/3xvbqebtzd9ihju"
      - "https://www.kuaishou.com/profile/3xxcvi49q2r52gu"
      - "https://www.kuaishou.com/profile/3xjwb88jf44whfk"
      - "https://www.kuaishou.com/profile/3x6u6nf5mfs5shq"
      - "https://www.kuaishou.com/profile/3xmkd327mnh8qe9"

  中式养生:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAPZNmFroK5J0Q9O-H_yooQl_n6sx7jqghMtvncZIDxsX9KdTQp6DsFKZQDgpTbYvS?from_tab_name=main&vid=7644151715096218233"
      - "https://www.douyin.com/user/MS4wLjABAAAAdaEJzB5PktBFNoMm8ilz5gsiABDsez13Iz1pLRXIHQs"
      - "https://www.douyin.com/user/MS4wLjABAAAAgIofZHSBY2pX1VC9SvghOKDh4det2eQIgpHHahBlU6g?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAY8uu__h89jhidK0d902eL4DRjPGh21JPK5xumcl4qBc?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAcp1LDAA5q1nfwV_U78A1MpwpXnhamstMLAi5ZDvFxB4-vqNFfz9h0yFWttOsq-1D?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAHMO7cXk2mW7C-Y3gsGzNZlLc2zi-U2mAH4hDJ-jqNDYql7wAv1qNRxg0QwMa6jIO?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAVfOjTFityNxA9zIIdluONULdwRDggVvl3QpoBuXg9Ygieqz7aL4y05m1iJgTBVav?from_tab_name=main"

  日式萝莉:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAA-Umb0f8NZnYix3w92h_ct0ScgFks0-UfhbFa2k6A_t-JdbHpFDrVhgEBAPOlq_iC?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAMsj2eJI4fbSbYpWU_El8pcqI0Id05lBriHdt9i0MvPBVOJU1Zbs9mWGm46XFAU8e?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAhQAUndMv1OHz-bv8omD6ZUe4ApswICr4BlDgtrnwJRkVEHUDe7o5g5TsdMS5yZu7?from_tab_name=main&relation=0&vid=7677449622923168369"
      - "https://www.douyin.com/user/MS4wLjABAAAASL-YY-pF7G-Y_EIC5JZOzKPbOeO81ghF1kcPQWI4bNo?from_tab_name=main&vid=7617825990501776313"
      - "https://www.douyin.com/user/MS4wLjABAAAAC1T7yWj_CMXzYGb-D6lE6d7nyY1sz87gJzNOLJfIv6XXMp0tfVJOyl5RsMgOfJ-S?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAb7oMNMENCBG0sP783E15yPgNkcKv38hZ5Db5mL9vghR5sny4cF4-wHGJt1tHJIf1?from_tab_name=main"

  治愈插花:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAA2zarBBPh8PWF0oEpW67k_g3Uui81PujuSaxLJnvJm_zJ26YzexOeqrkUwwj-coVy"
      - "https://www.douyin.com/user/MS4wLjABAAAADhS9WKo3r3oorvfREDT8xs6asZcAOXAwltEfxk0ZKRgAAnTPgG5fOkKk8qtMHncn"
      - "https://www.douyin.com/user/MS4wLjABAAAAZE4KdYytix5HdC9kPMi0OD78Omi6-VHUVf4CCYVoP1RkeRgpaLq5C77jmZIZ7wFP"
      - "https://www.douyin.com/user/MS4wLjABAAAASheo93P7w46i6h5ow35cgiK7pGiOzoIdohp0fW-fJ_Q"
      - "https://www.douyin.com/user/MS4wLjABAAAA__vgsfQpOZnRXH4y4qDMAOda3ImaSQZuvJ36zc7DShI"
      - "https://www.douyin.com/user/MS4wLjABAAAAkYgRtCc3Xw1oegQ0g0FITPF3o0vs6OljtW3qF5CaXsysiUN8yW4NkJ4eCD4f_T8q"
      - "https://www.douyin.com/user/MS4wLjABAAAAduTKwTQyXbeZziTXYy2bWi8kTTMFTr0947X48xx71fTscMCt2vnKV41gHhhvjVIa"
      - "https://www.douyin.com/user/MS4wLjABAAAAIpCcNfHbiHh96nx2KyZ8sbQLTlw_9Q1R4HSqkH2ZZNS-nq8lpFGBvpltxtJjAoDz"
      - "https://www.douyin.com/user/MS4wLjABAAAAMGmEf_BxpwRqonlQFpU6KsgblVnELPNs-9Vvs_Rg_Xk"
      - "https://www.douyin.com/user/MS4wLjABAAAAgT3cIUcA0PiG-9-rLNEg6h_urYM8hwz74ijEPc7RQRU"
      - "https://www.douyin.com/user/MS4wLjABAAAAZNpzxA5Lp5yUpN7jK4B8EimGkJwMnDgvU_2_2PXWEfTBANoBiZRwYuQpUNtjdykE"

  武颜集萃:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAASZ5YgijMX8nIuyfFvTIyKxfIr03bQjinktcBnlPBgUfvMbKPRsLuEronp0J0DLhz?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAWaEM4pX5eAY3IL5cQVd3zDziiwIUPQLJTNYfIqqd4IM"
      - "https://www.douyin.com/user/MS4wLjABAAAA5KFa1HS9RFUqAGfjX41jpKvUFBC-YSUtJf5F-wjpO7Y"
      - "https://www.douyin.com/user/MS4wLjABAAAAgGJQl08Ee-pjdwBiPJRJHGdYcU9fXWnPa-IxB9-Xqv8"
      - "https://www.douyin.com/user/MS4wLjABAAAAOUSGLRXOQ0Atq--fICZWuAFv_VkRZ3zi94zSx_WaGDo?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAHWWsw2OAJcPPWaFioI4Ulzm83eOvh-XWBnsG0WNzNl4?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAyC9-V3j0cStZmAkoV1xkilkSj7Tdl6eAVnvDc03G91UUH1NQywzI1-TDTWVOmlET?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAYeMODUj3H0ZtV8rd1fdHxZIEpfc9QuztMWZ30nwvSjQ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAl-qlmA8pvymFPQlJXhFTsu9iBqhxhYn6yeV6Lm9refk"

  舞男:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAPlangt8LdeViUePuFi4LbLsiIEWfzkjGE0elzCyh1lCN8raPIYfnA9JmDz54CXvV?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA7M9bUUvaAXxGgVUlOi1E5xSndBwsf5XR3aVmVQnCFTw?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAJeNKP1HZCKoDEzIMKfztInnFvWmfjmDctKZdKa9Q3ILCOI7KckzAsQ73Ain1VgsL?from_tab_name=main&vid=7673450385730696628"
      - "https://www.douyin.com/user/MS4wLjABAAAAlZ3w38jN3ypdH7I8MlAbz3iP0fWcZT_1e0YK7EOMtxg?from_tab_name=main&vid=7654169174403934153"
      - "https://www.douyin.com/user/MS4wLjABAAAADYyzvih681JhHdw6v66RVOOsZGhCPcdzuSF27_9y59E?from_tab_name=main&vid=7677783791046207929"
      - "https://www.douyin.com/user/MS4wLjABAAAAjX_TljkbF0XG6C9ceP8fCXAsiU8OWu4FIZFqdN9RTCs0ZBbzFNitTjvT5Wu9buX_?from_tab_name=main&vid=7593663269555020378"
      - "https://www.douyin.com/user/MS4wLjABAAAAjFRh5TNcjGbJehBDdf7rOBzZH3ZQnfqgvp1Hcdcy31gStEgrlcCMHTB3Jw-DI76_?from_tab_name=main&showSubTab=video&showTab=post"

  御马飞驰:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAss26ZBTIgAv1PFOVli7bQ09dZEzTuh-bAVbI6CJcEIKcS6ajkUwrbbynkTDbgZxe?from_tab_name=main&vid=7591445740737636800"
      - "https://www.douyin.com/user/MS4wLjABAAAAfRzHs4lvZrTOfwpMb_-UlXmR1B2UodBvKTV_B5ed-Tc?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAasn_CxD5u1cY-tiX8yp2AZTLSrW90t6TXE3q6MVKPgE?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA1-lvvXuL6fgGnmvGZk2d4H-oSDhSdk8B2Plwi_HZ-Nc?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAbYKfkYEXZXHq8i2ST0xo9g5R1wdCcQsnikOViBzmi3jJjIY2QNk32OB12axbUZOE?from_tab_name=main&vid=7686659137698198473"
      - "https://www.douyin.com/user/MS4wLjABAAAA0WJFbQYUIQMipNjVg4_HgmTSIxuplV6Hema0bX-FWhM?from_tab_name=main"
      
  汉服秀:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAA3LwchTkxOH2HyKxrXEx1zdZgDbEoJQYk2g9SP0Ql6Tjl8jmBiqv9ABQggT-ueaQ-?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAFhVcECtr7F08mRTTMUb2KCXhQWKTfWgm59wXtZimVQc"
      - "https://www.douyin.com/user/MS4wLjABAAAAPX8VrLeZNtW5-vQMQYPqK094KbBkHRFZYYQcxuT0eZ5aCMN_5aimMxU-ZA_htRnz"
      - "https://www.douyin.com/user/MS4wLjABAAAAbzEAyAdKKVhmvz9F6nZMn5oSes36ijX8CgICrCjL2Gg"
      - "https://www.douyin.com/user/MS4wLjABAAAAcBN_7TDxFF9N8fONUvvjPAPlOiyp1GIJHbmianyaZZg"
      - "https://www.douyin.com/user/MS4wLjABAAAA2E5GkrKc9k5uAr7jI3zftTEVUIWsTmQIHfKRcsB5xXw"
      - "https://www.douyin.com/user/MS4wLjABAAAAItuBv_SbaBGCG38ec86nUgtqTqo8GqZ7dvlwD-lSu8M"
      - "https://www.douyin.com/user/MS4wLjABAAAAUTlhcQ-khY0DTGtsJcOWHxEstb0UZM-2iRoSOqlPnnzDif8nLTAlPc6GjbFOoEy9"
      - "https://www.douyin.com/user/MS4wLjABAAAAEArh6xs6_teauzh1KM9pIDyevKHpVEDMAH5YKV2PLdI"
      - "https://www.douyin.com/user/MS4wLjABAAAAkD_mGQDE1vHWDyv2Dufr5I8R9imdnY3bqf8OOjvDIc8O-dX0oRNqlek0r5VC6cSI"
      - "https://www.douyin.com/user/MS4wLjABAAAA3Py5UM3oSqbB3LfjdpTOUx-3Yb-RPIs_2PbSxbQPvSvLTLw7uZoHdocfvccr_5w6"

  中国舞:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAYJodh6P_o7iy28LMJKJvXwsTtWx7dTMmqGAvmpllAjY"
      - "https://www.douyin.com/user/MS4wLjABAAAAGhPFeH61oaYrqK-XuNOexX9ES9w9GUwPqLdbp8roEtE?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA-grFTFnpjyCcGIqYpEPfIx1ask_1bLi55YNeoL9ALgAW1evArQ0S-p9BqGa-V6UJ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAPJX_lzrk9W277Z0_eW0xKOYy-zmhiyGTZ7w0BUBsR_k?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAMSEZdp68AQ1l2JLzvzkcM40XFc0a2LGoV67RsRKX6TQ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAApN7bzFSJvLry5loHzTjTUUTyVwzHdsFFle2o0XG9TX4?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAZ_XNKzbNDoqiMThEc11PkiGzOZQQKfl5_dsedtDPjoQ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAOVesBQ8UUycNmTumdrN2cnw8Z5rrFwpwqLcv-XwWWkOsHIqbGHGv38fRi5bnKmaJ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAXbOATGoi2YLK8jvFP8D4-p4a40U411psk3-5QWrl_031JJ1CLBq1nW7cikr1FcGV?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAgxfDJJkFVwxjiIhSwkS2FePxsZSwV8MXbifkBnlTAqt9yzXtFWrdPBbpjyR86XIs?from_tab_name=main"
      
  中国美食制作:
    source_accounts:
      - "https://www.douyin.com/user/MS4wLjABAAAAS2emYzTYdteuFsNKLDN-CQWOjz1YE3pD0AqdD0tdoxo?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAS2emYzTYdteuFsNKLDN-CQWOjz1YE3pD0AqdD0tdoxo?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAGYnGbB4fkVzcaLAi1tGvflql8t8KU9BPZkkXQvyRWX2_5IfmFF-jtgYILbWKVXF-?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAP74P8ql1dQAs3ljNLIQ88bYskKfa_PaKgcC_zcNinNo7MXJLKLSUngOCkfhyRb_j?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAW_rdRMeR5kbVcGwbi05AGmftOz1MZ7IiOuWZKzRUs1b4Cfh1q0sgNk9Zs0GXZ5OZ?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAJRcu63en3erHIRgARcCz94SIjTY776HivC2NnDGSxc7mYUdmb4NxUMS6-QpsM9P6?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAcBRt9DgsTgT9puik0S7myqWStstMGoWnFfEvedfOHeSBAqJjcBpKwvEYL7ytN0ph?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA5geJ1b0LH1LaF1QzenF8nVfVGN9Ifz3CaV1uJlA14Q5YbKYtSwV8l5RoAXsIFIcv?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAAbhp8trFOYLwr7NdY8kNZeboXDsf1jAyyfDR8VNRcWsg?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAATSdZFfVrkiqexr2GmSq1ZdIkPiOUCIbjUcjFvXmUaRY?from_tab_name=main"
      - "https://www.douyin.com/user/MS4wLjABAAAA_P1affovY6wWNhor-3qj_XyBjLHkOi1hqOZYptLEaZKlpEbWtCWiis2yXJmpVMhm?from_tab_name=main"